title: "Kaare Øster"
description: "Fagforfatter · Rejser · Projekter · Udgivelser"
baseurl: "/kaareoester"
url: "https://eskehagen.github.io"
lang: da

author:
  name: "Kaare Øster"
  email: "kaos@kaareoester.dk"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# Pagination
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

paginate: 8
paginate_path: "/indlaeg/side/:num/"

# Collections
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
